include: package:flutter_lints/flutter.yaml

analyzer:

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: true
    avoid_multiple_declarations_per_line: true
    avoid_null_checks_in_equality_operators: true
    avoid_print: true
    avoid_renaming_method_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    eol_at_end_of_file: true
    hash_and_equals: false
    implementation_imports: true
    overridden_fields: false
    prefer_adjacent_string_concatenation: true
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_collection_literals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    sort_pub_dependencies: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    use_build_context_synchronously: false
    use_key_in_widget_constructors: true
    use_enums: true