name: calendar_alarm
description: "An app to get alarms for the existing events in your calendars"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: 3.27.3

dependencies:
  alarm: ^5.1.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  logging: ^1.3.0
  manage_calendar_events: ^2.0.3
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
