name: Static code analysis

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  lint:
    name: Validate format and analyze code
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version-file: pubspec.yaml

      # Get dependencies
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: dart fix --apply
      - run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
